
server:
  port: 9000

eureka:
  instance:
    preferIpAddress: true
    instance-id: spotzuul
  client:
    service-url:
      defaultZone: http://admin:Cube4302@localhost:8888/eureka/

spring:
 application: zuul-service-filter


ribbon:
  eureka:
    enabled: true
